### ISSUE TITLE
PSR-2 Violations

### ISSUE THREAD

**Issue by GrahamCampbell** [cartalyst/collections#1]
You have code like this, which violates the PSR-2 standard:

``` php
    if ( ! array_key_exists($segment, $item)) {
        return null;
    }
```

PSR-2 says that you are not allowed to have a space before that `!`, but says nothing about any spaces following it.

Some example code from PSR-1:

``` php
if (! function_exists('bar')) {
    function bar()
    {
        // function body
    }
}
```

**Comment by brunogaspar** [comment]
It's fine.

**Comment by GrahamCampbell** [comment]
> It's fine.

So the readme should updated to say, actually, you don't follow PSR-2.

**Comment by brunogaspar** [comment]
Just because a minor space we have, we don't follow PSR-2? Cmon, give me a break.
